name: CI

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set up pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.9

      # Set up Node.js environment
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x # Use the same Node.js version as your local setup
          cache: "pnpm"

      # List files for debugging to confirm lockfile presence
      - run: ls -la # Check for pnpm-lock.yaml presence
      - run: pnpm -v
      - run: node -v

      # Install dependencies
      # - run: pnpm install --frozen-lockfile
      - run: pnpm install --no-frozen-lockfile
      - run: npx tsc -v

      # Run linting and build steps
      - run: pnpm run lint && pnpm run build
